apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: batch-hello
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: argocd-learn-apps
  source:
    repoURL: https://github.com/anomaly51/argocd-learn-gitops.git
    targetRevision: main
    path: apps/batch-hello/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-learn-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

