apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-blackbox-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: argocd-learn-apps
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 11.10.0
    helm:
      releaseName: helm-blackbox-exporter
      valuesObject:
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-learn-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

