apiVersion: v1
kind: Service
metadata:
  name: argocd-learn-smoke
  labels:
    app.kubernetes.io/name: argocd-learn-smoke
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-learn-smoke
  ports:
    - name: http
      port: 80
      targetPort: http

